name: Ping Websites

on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every 1 minutes
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Ping websites
        run: |
          curl -s https://dashboard-e9g1.onrender.com/ > /dev/null
          curl -s https://help-responses.onrender.com/ > /dev/null
          curl -s https://esp8266-control.onrender.com/ > /dev/null
          
